// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// distant_matrix
arma::mat distant_matrix(const arma::mat& obj, const arma::umat& miss);
RcppExport SEXP _rknnim_distant_matrix(SEXP objSEXP, SEXP missSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type obj(objSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type miss(missSEXP);
    rcpp_result_gen = Rcpp::wrap(distant_matrix(obj, miss));
    return rcpp_result_gen;
END_RCPP
}
// find_knn_indices_arma
arma::uvec find_knn_indices_arma(const arma::vec& distances, arma::uword k);
RcppExport SEXP _rknnim_find_knn_indices_arma(SEXP distancesSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type distances(distancesSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(find_knn_indices_arma(distances, k));
    return rcpp_result_gen;
END_RCPP
}
// impute_knn_arma
arma::mat impute_knn_arma(const arma::mat& obj, const arma::umat& miss, const arma::uword k);
RcppExport SEXP _rknnim_impute_knn_arma(SEXP objSEXP, SEXP missSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type obj(objSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type miss(missSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(impute_knn_arma(obj, miss, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rknnim_distant_matrix", (DL_FUNC) &_rknnim_distant_matrix, 2},
    {"_rknnim_find_knn_indices_arma", (DL_FUNC) &_rknnim_find_knn_indices_arma, 2},
    {"_rknnim_impute_knn_arma", (DL_FUNC) &_rknnim_impute_knn_arma, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_rknnim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
