# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

row_index <- function(n) {
    .Call(`_rknnim_row_index`, n)
}

calc_distant_cpp <- function(v1, v2, m1, m2) {
    .Call(`_rknnim_calc_distant_cpp`, v1, v2, m1, m2)
}

partial_sort_cpp <- function(distances, k) {
    .Call(`_rknnim_partial_sort_cpp`, distances, k)
}

impute_knn_cpp <- function(obj, miss, k) {
    .Call(`_rknnim_impute_knn_cpp`, obj, miss, k)
}

