# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_squared_distance <- function(obj, miss, idx1, idx2, total_rows) {
    .Call(`_rknnim_calc_squared_distance`, obj, miss, idx1, idx2, total_rows)
}

distant_matrix <- function(obj, miss, index) {
    .Call(`_rknnim_distant_matrix`, obj, miss, index)
}

find_knn_indices_arma <- function(distances, k) {
    .Call(`_rknnim_find_knn_indices_arma`, distances, k)
}

impute_knn_arma <- function(obj, miss, k) {
    .Call(`_rknnim_impute_knn_arma`, obj, miss, k)
}

