# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

col_index <- function(i, p) {
    .Call(`_rknnim_col_index`, i, p)
}

calc_distant_arma <- function(v1, v2, m1, m2) {
    .Call(`_rknnim_calc_distant_arma`, v1, v2, m1, m2)
}

find_knn_indices_arma <- function(distances, k) {
    .Call(`_rknnim_find_knn_indices_arma`, distances, k)
}

#' @export
impute_knn_arma <- function(obj, miss, k) {
    .Call(`_rknnim_impute_knn_arma`, obj, miss, k)
}

